theme: jekyll-theme-architect
github:
  inicio_url: https://jbasantech.github.io/basanbolt/
  preparacion_url: https://jbasantech.github.io/basanbolt/preparacion.html
  raspberrypi_url: https://jbasantech.github.io/basanbolt/raspberrypi.html
  seguridad_url: https://jbasantech.github.io/basanbolt/seguridad.html
  privacidad_url: https://jbasantech.github.io/basanbolt/privacidad.html
  bitcoin_url: https://jbasantech.github.io/basanbolt/bitcoin.html
  lightning_url: https://jbasantech.github.io/basanbolt/lightining.html
